= JavalessMC

=== THIS PROJECT IS NOT ENDORSED, AFFILIATED OR OTHERWISE APPROVED BY MOJANG STUDIOS AND / OR MICROSOFT. YOU NEED TO OWN A MINECRAFT ACCOUNT IN ORDER TO USE THIS PROJECT, AND IT DOES NOT ENABLE PIRACY BY ITSELF

JavalessMC is a minecraft headless instance that work in C++. Its goal is to provide a fast and memory efficient framework to build Minecraft bots.

*THIS TOOL IS A WORK IN PROGRESS AND MAY NOT WORK AS EXPECTED. PLEASE BE PATIENT UNTIL WE MAKE A WORKING SOLUTION !*

== building

run the build.sh batch file in the scripts folder.

== Install plugins

depending on your OS, download either a .dll or .so of the plugin, and put it in the plugins folder.

If this folder does not exist, create it yourself. JavalessMC alone is useless, as it just create a player that do nothing.

== Debugging

in CMakeLists.txt, change IS_DEBUG to ON to run test and have additional debug information

== Create plugins

In the future, an api and an exemple will be published, with documentation. For now, please wait until we get to this part of developpement.

== Credits : 

[cols="~,~"]
|===

| https://github.com/SomeBoringNerd[SomeBoringNerd (Morgane)]
| main developper, plugin loader, event system

| https://github.com/TaxMachine[TaxMachine]
| main developper, all of the networking

|===
